### ISSUE TITLE
Missing seed corpus (unbound)

### ISSUE THREAD

**Issue by wcshim40** [aflchurn/aflchurnbench#1]
First of all, thank you for releasing 'aflchurnbench'. I've seen your recent work, "Return Gray Box Fuzzing," and I've tried to set up a benchmark environment to reproduce your work for further research. 

However, the 'unbound' project recently removed 'fuzz_1_fuzzer_seed_corpus.zip' from [oss-fuzz ](https://oss-fuzz-build-logs.storage.googleapis.com/index.html#unbound) so I have trouble setting up your benchmark environment for 'unbound_fuzz_1_fuzzer'. 

The URL of seed corpus was "https://github.com/luisx41/fuzzing-corpus/raw/master/projects/unbound/fuzz_1_fuzzer_seed_corpus.zip", but unfortunately it is no longer available.

I think there is a possibility that 'fuzz_1_fuzzer_seed_corpus.zip' would remain in your local experimental environment. So I'd like to ask if it's possible to check and share the file if possible.

**Comment by RosenZhu** [comment]
Yes, the benchmark may have problems. Since [Fuzzbench](https://github.com/google/fuzzbench) itself is continuously maintained, and sometimes the problems come from the Fuzzbench. Therefore, our aflchurnbench may have some problems. We will try to fix those problems when we have time. (Our own experiments also find that some applications cannot run correctly due to the update of oss-fuzz or fuzzbench. And we select other applications.)

I think you can remove the `unbound` for the current experiments?  Or you can try different regression bugs for `unbound`?

**Comment by wcshim40** [comment]
Thank you for your prompt response. Yes, I'll look for another regression bug as you recommended. Thank you again.

**Comment by RosenZhu** [comment]
> I think there is a possibility that 'fuzz_1_fuzzer_seed_corpus.zip' would remain in your local experimental environment. So I'd like to ask if it's possible to check and share the file if possible.

We ran our experiments on Google's server. So we don't have those data.
